export type BuildingCategory = 'academic' | 'residential' | 'dining' | 'administrative' | 'athletics' | 'library' | 'recreation' | 'parking' | 'health';

export interface CampusBuilding {
  id: string;
  name: string;
  abbreviation: string;
  lat: number;
  lon: number;
  categories: BuildingCategory[]; // Primary category first, then secondary
  department: string;
  description: string;
  imageUrl?: string;
}

export const CATEGORY_ICONS: Record<BuildingCategory, { path: string; label: string }> = {
  academic: {
    path: 'M8 0L0 4v1h16V4L8 0zM1 6v7h2V6H1zm4 0v7h2V6H5zm4 0v7h2V6H9zm4 0v7h2V6h-2zM0 14v2h16v-2H0z',
    label: 'Academic',
  },
  residential: {
    path: 'M8 0L0 6v10h6v-5h4v5h6V6L8 0zm0 9a2 2 0 110-4 2 2 0 010 4z',
    label: 'Residential',
  },
  dining: {
    path: 'M2 0v7c0 1.1.9 2 2 2h1v7h2V9h1c1.1 0 2-.9 2-2V0H8v5H6V0H4v5H2V0zm10 0v6h2v4h-2v6h2V10h2V4c0-2.2-1.8-4-4-4z',
    label: 'Dining',
  },
  administrative: {
    path: 'M8 0L0 3v2h16V3L8 0zM2 6v8H0v2h16v-2h-2V6h-3v8H9V6H7v8H5V6H2z',
    label: 'Administrative',
  },
  athletics: {
    path: 'M12 4a4 4 0 00-8 0c0 1.5.8 2.8 2 3.5V16h4V7.5c1.2-.7 2-2 2-3.5zm-4-2a2 2 0 110 4 2 2 0 010-4z',
    label: 'Athletics',
  },
  library: {
    path: 'M8 0L1 3v13h2V5l5-2 5 2v11h2V3L8 0zM4 6v9h2V7l2-.8 2 .8v8h2V6L8 4 4 6z',
    label: 'Library',
  },
  recreation: {
    path: 'M8 0a3 3 0 100 6 3 3 0 000-6zM4 7c-1.1 0-2 .9-2 2v5h2v2h8v-2h2V9c0-1.1-.9-2-2-2H4z',
    label: 'Recreation',
  },
  parking: {
    path: 'M2 0C.9 0 0 .9 0 2v12c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V2c0-1.1-.9-2-2-2H2zm4 3h4c1.7 0 3 1.3 3 3s-1.3 3-3 3H8v4H6V3zm2 4h2c.6 0 1-.4 1-1s-.4-1-1-1H8v2z',
    label: 'Parking',
  },
  health: {
    path: 'M14 5h-3V2c0-1.1-.9-2-2-2H7c-1.1 0-2 .9-2 2v3H2c-1.1 0-2 .9-2 2v2c0 1.1.9 2 2 2h3v3c0 1.1.9 2 2 2h2c1.1 0 2-.9 2-2v-3h3c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2z',
    label: 'Health',
  },
};


// Category icons as SVG paths (16x16 viewBox)
// WKU Campus Buildings - Expanded with South Campus and Parking
export const CAMPUS_BUILDINGS: CampusBuilding[] = [
  // === ACADEMIC BUILDINGS ===
  {
    id: 'cherry',
    name: 'Cherry Hall',
    abbreviation: 'CH',
    lat: 36.98751,
    lon: -86.45114,
    categories: ['administrative', 'academic'],
    department: 'Administration & Liberal Arts',
    description: "WKU's most iconic building, named after founder Henry Hardin Cherry. Built in 1937, this Collegiate Gothic structure sits atop 'The Hill' and serves as the administrative heart of the university.",
  },
  {
    id: 'engineering',
    name: 'Engineering and Biological Sciences Building',
    abbreviation: 'EBS',
    lat: 36.98588,
    lon: -86.44899,
    categories: ['academic'],
    department: 'Ogden College of Science & Engineering',
    description: 'Home to the departments of Biology and Engineering. The complex features specialized labs for civil, mechanical, and electrical engineering, as well as the Biotechnology Center.',
  },
  {
    id: 'est',
    name: 'Environmental Sciences & Technology',
    abbreviation: 'EST',
    lat: 36.98607,
    lon: -86.44997,
    categories: ['academic'],
    department: 'Earth, Environmental, and Atmospheric Sciences',
    description: 'Home to the Meteorology, Geology, and Geography programs. The building features the Kentucky Climate Center and high-tech GIS mapping laboratories.',
  },
  {
    id: 'fac',
    name: 'Fine Arts Center',
    abbreviation: 'FAC',
    lat: 36.98646,
    lon: -86.45323,
    categories: ['academic'],
    department: 'Potter College of Arts & Letters',
    description: 'The Ivan Wilson Fine Arts Center houses the Art, Music, and Theatre & Dance departments. Features galleries, performance spaces, and specialized studios.',
  },
  {
    id: 'grh',
    name: 'Gary A. Ransdell Hall',
    abbreviation: 'GRH',
    lat: 36.98205,
    lon: -86.45613,
    categories: ['academic'],
    department: 'College of Education & Behavioral Sciences',
    description: 'A state-of-the-art facility for future educators. It features high-tech "classrooms of the future" and the World Council for Gifted and Talented Children.',
  },
  {
    id: 'grise',
    name: 'Grise Hall',
    abbreviation: 'GH',
    lat: 36.98565,
    lon: -86.45439,
    categories: ['academic'],
    department: 'Potter College of Arts & Letters',
    description: 'A major academic hub housing English, History, Philosophy & Religion, and Political Science. Named after Finley C. Grise, a former Dean of the College.',
  },
  {
    id: 'hardin',
    name: 'Hardin Planetarium',
    abbreviation: 'HPL',
    lat: 36.98649,
    lon: -86.44959,
    categories: ['academic'],
    department: 'Physics & Astronomy',
    description: "Kentucky's second-oldest planetarium, offering free public shows and educational programs. It features a 40-foot dome for celestial observations.",
  },
  {
    id: 'jrh',
    name: 'Jody Richards Hall',
    abbreviation: 'JRH',
    lat: 36.98291,
    lon: -86.45649,
    categories: ['academic'],
    department: 'School of Media & Communication',
    description: "Houses the campus radio and TV stations, the College Heights Herald, and the Talisman. It features the 'Hub' 24-hour computer lab.",
  },
  {
    id: 'thompson',
    name: 'Kelly Thompson Hall',
    abbreviation: 'TC',
    lat: 36.98665,
    lon: -86.44898,
    categories: ['academic'],
    department: 'Ogden College of Science & Engineering',
    description: "Named for WKU's third president, this building houses the Department of Physics and Astronomy, including specialized research laboratories.",
  },
  {
    id: 'ogden',
    name: 'Ogden College Hall',
    abbreviation: 'OCH',
    lat: 36.98684,
    lon: -86.44822,
    categories: ['academic'],
    department: 'Ogden College of Science & Engineering',
    description: 'A premier science facility featuring the Dean’s Office, a 300-seat auditorium, and high-tech laboratories for biology, chemistry, and physics.',
  },
  {
    id: 'snell',
    name: 'Snell Hall',
    abbreviation: 'SNL',
    lat: 36.98639,
    lon: -86.44862,
    categories: ['academic'],
    department: 'Ogden College of Science & Engineering',
    description: 'Connects to Thompson Complex and houses advanced laboratories for Chemistry and Biology, serving as a key facility for scientific research.',
  },
  {
    id: 'women',
    name: "Women's Studies Center",
    abbreviation: 'WSC',
    lat: 36.98588,
    lon: -86.45065,
    categories: ['academic'],
    department: 'Diversity & Community Studies',
    description: 'The administrative and social hub for the Gender & Women’s Studies program, offering a resource library and meeting space for students.',
  },

  // === SOUTH CAMPUS ===
  {
    id: 'knicely',
    name: 'Knicely Conference Center',
    abbreviation: 'KCC',
    lat: 36.96165,
    lon: -86.46740,
    categories: ['academic', 'administrative'],
    department: 'Continuing & Professional Development',
    description: 'A multi-purpose conference and event facility located on South Campus. It hosts university functions, community events, and professional development workshops.',
  },
  {
    id: 'south_academic',
    name: 'South Campus Academic Wing',
    abbreviation: 'SCAW',
    lat: 36.96220,
    lon: -86.46820,
    categories: ['academic'],
    department: 'General Education & Testing',
    description: 'Located at the South Campus complex, this wing houses classrooms, the Distance Learning Testing Center, and various health-related community services.',
  },

  // === ADMINISTRATIVE ===
  {
    id: 'alumni',
    name: 'Eva and Jim Martens Alumni Center',
    abbreviation: 'AAC',
    lat: 36.98965,
    lon: -86.45116,
    categories: ['administrative'],
    department: 'WKU Alumni Association',
    description: 'A welcoming venue for alumni and guests. It serves as a bridge between the campus community and the global network of Hilltopper graduates.',
  },
  {
    id: 'wab',
    name: 'Wetherby Administration Building',
    abbreviation: 'WAB',
    lat: 36.98737,
    lon: -86.45378,
    categories: ['administrative'],
    department: 'University Administration',
    description: "The primary administrative building housing the President’s Office, Registrar, Financial Aid, and Admissions.",
  },

  // === ATHLETICS ===
  {
    id: 'diddle',
    name: 'E.A. Diddle Arena',
    abbreviation: 'DA',
    lat: 36.98646,
    lon: -86.45763,
    categories: ['athletics'],
    department: 'WKU Athletics',
    description: 'The historic home of Hilltopper and Lady Topper Basketball. Famous for the waving of the Red Towel and its energetic atmosphere.',
  },
  {
    id: 'stadium',
    name: 'Houchens-L.T. Smith Stadium',
    abbreviation: 'STAD',
    lat: 36.98480,
    lon: -86.45943,
    categories: ['athletics'],
    department: 'WKU Athletics',
    description: "Home of Hilltopper Football. The stadium includes Feix Field and the Harbaugh Club, seating over 22,000 fans for game days.",
  },

  // === DINING & STUDENT LIFE ===
  {
    id: 'dsu',
    name: 'Downing Student Union',
    abbreviation: 'DSU',
    lat: 36.98358,
    lon: -86.45624,
    categories: ['dining', 'administrative'],
    department: 'Student Affairs',
    description: "The central hub for student life. Features the main food court, the WKU Store, a movie theater, and student organization offices.",
  },

  // === HEALTH ===
  {
    id: 'hs',
    name: 'Health Services',
    abbreviation: 'HS',
    lat: 36.98238,
    lon: -86.45771,
    categories: ['health'],
    department: 'Student Health Services',
    description: 'An on-campus clinic providing primary care, immunizations, and a full-service pharmacy for students and faculty.',
  },

  // === LIBRARY ===
  {
    id: 'Library',
    name: 'Raymond Cravens Library',
    abbreviation: 'LIB',
    lat: 36.98560,
    lon: -86.45259,
    categories: ['library'],
    department: 'University Libraries',
    description: "WKU's main nine-story library offering extensive research collections and quiet study floors with panoramic views.",
  },
  {
    id: 'Commons',
    name: 'The Commons at Helm Library',
    abbreviation: 'COM',
    lat: 36.98560,
    lon: -86.45259,
    categories: ['library', 'dining'],
    department: 'University Libraries',
    description: 'A modern food hall and intellectual hub blending library resources with multiple dining options and collaborative workspaces.',
  },

  // === PARKING ===
  {
    id: 'adams_lot',
    name: 'Adams Street Lot',
    abbreviation: 'ASL',
    lat: 36.98920,
    lon: -86.45210,
    categories: ['parking'],
    department: 'Parking & Transportation',
    description: 'Large surface lot providing commuter parking near the northern edge of campus, close to the Kentucky Building and Alumni Center.',
  },
  {
    id: 'alumni_garage',
    name: 'Alumni Square Garage',
    abbreviation: 'ASG',
    lat: 36.99025,
    lon: -86.45030,
    categories: ['parking'],
    department: 'Parking & Transportation',
    description: 'A gated parking garage serving the Alumni Center, WKU Apartments, and local businesses. Features visitor hourly parking.',
  },
  {
    id: 'creason_lot',
    name: 'Creason Lot',
    abbreviation: 'CL',
    lat: 36.98080,
    lon: -86.46240,
    categories: ['parking'],
    department: 'Parking & Transportation',
    description: 'Extensive surface parking lot on the south side of campus, primarily used for commuter students and overflow during major events.',
  },
  {
    id: 'ps1',
    name: 'Parking Structure 1',
    abbreviation: 'PS1',
    lat: 36.98270,
    lon: -86.45505,
    categories: ['parking'],
    department: 'Parking & Transportation',
    description: "Located near DSU. It provides visitor parking and houses the Planning, Design & Construction and Parking & Transportation offices.",
  },
  {
    id: 'ps2',
    name: 'Parking Structure 2',
    abbreviation: 'PS2',
    lat: 36.98530,
    lon: -86.45115,
    categories: ['parking'],
    department: 'Parking & Transportation',
    description: 'Located near the Science Campus and Smith Stadium. Primarily serves commuter students and visitors for athletic events.',
  },
  {
    id: 'ps3',
    name: 'Parking Structure 3',
    abbreviation: 'PS3',
    lat: 36.98180,
    lon: -86.46110,
    categories: ['parking'],
    department: 'Parking & Transportation',
    description: 'A modern parking deck located near the First Year Village and Pearce-Ford Tower, serving housing students and visitors.',
  },

  // === RECREATION ===
  {
    id: 'pc',
    name: 'Preston Center',
    abbreviation: 'PC',
    lat: 36.98306,
    lon: -86.45893,
    categories: ['recreation'],
    department: 'Campus Recreation',
    description: "WKU's premier fitness facility, featuring a weight room, natatorium, and the Outdoor Recreation Adventure Center.",
  },

  // === RESIDENTIAL ===
  // (Residential entries same as previous, keeping your sorted order)
  {
    id: 'bates',
    name: 'Bates-Runner Hall',
    abbreviation: 'BRH',
    lat: 36.98571,
    lon: -86.45592,
    categories: ['residential'],
    department: 'Housing & Residence Life',
    description: 'A suite-style residence hall located near the top of the hill, offering private living with shared bathrooms.',
  },
  {
    id: 'douglas',
    name: 'Douglas Keen Hall',
    abbreviation: 'DK',
    lat: 36.98203,
    lon: -86.46049,
    categories: ['residential'],
    department: 'Housing & Residence Life',
    description: 'A community-style hall located on the south end of campus near the Preston Center and Pearce-Ford Tower.',
  },
  {
    id: 'gilbert',
    name: 'Gilbert Hall',
    abbreviation: 'GIL',
    lat: 36.98764,
    lon: -86.45561,
    categories: ['residential'],
    department: 'Housing & Residence Life',
    description: 'A community-style residence hall located in "The Valley," known for its social atmosphere.',
  },
  {
    id: 'hugh',
    name: 'Hugh Poland Hall',
    abbreviation: 'HP',
    lat: 36.98197,
    lon: -86.45969,
    categories: ['residential'],
    department: 'Housing & Residence Life',
    description: 'A community-style hall located near the stadium, popular among sports fans and athletes.',
  },
  {
    id: 'mccormack',
    name: 'McCormack Hall',
    abbreviation: 'MCH',
    lat: 36.98824,
    lon: -86.45588,
    categories: ['residential'],
    department: 'Housing & Residence Life',
    description: 'A six-story, community-style residence hall in the valley area, offering easy access to north campus.',
  },
  {
    id: 'mclean',
    name: 'McLean Hall',
    abbreviation: 'MCL',
    lat: 36.98620,
    lon: -86.45497,
    categories: ['residential'],
    department: 'Housing & Residence Life',
    description: 'A charming, historic residence hall located near Cherry Hall and the top of the Hill.',
  },
  {
    id: 'meredith',
    name: 'Meredith Hall',
    abbreviation: 'MER',
    lat: 36.98046,
    lon: -86.45983,
    categories: ['residential'],
    department: 'Housing & Residence Life',
    description: 'A suite-style hall located in the south campus area, offering close proximity to the South Lawn.',
  },
  {
    id: 'minton',
    name: 'Minton Hall',
    abbreviation: 'MIN',
    lat: 36.98429,
    lon: -86.45605,
    categories: ['residential'],
    department: 'Housing & Residence Life',
    description: "The primary residence hall for the Mahurin Honors College, featuring dedicated study lounges.",
  },
  {
    id: 'munday',
    name: 'Munday Hall',
    abbreviation: 'MU',
    lat: 36.98466,
    lon: -86.45459,
    categories: ['residential'],
    department: 'Housing & Residence Life',
    description: "A modern, suite-style residence hall named after WKU's first African American graduate, Margaret Munday.",
  },
  {
    id: 'normal',
    name: 'Normal Hall',
    abbreviation: 'NH',
    lat: 36.98060,
    lon: -86.45882,
    categories: ['residential'],
    department: 'Housing & Residence Life',
    description: 'Part of the First Year Village, this pod-style hall is designed for Living Learning Communities (LLCs).',
  },
  {
    id: 'pft',
    name: 'Pearce-Ford Tower',
    abbreviation: 'PFT',
    lat: 36.98120,
    lon: -86.46005,
    categories: ['residential'],
    department: 'Housing & Residence Life',
    description: "At 27 stories, PFT is one of the tallest residence halls in the country and houses the 'Fresh Food Company'.",
  },
  {
    id: 'regents',
    name: 'Regents Hall',
    abbreviation: 'RE',
    lat: 36.98155,
    lon: -86.45820,
    categories: ['residential'],
    department: 'Housing & Residence Life',
    description: 'A modern pod-style residence hall in the First Year Village, focused on social and academic connection.',
  },
  {
    id: 'rodes',
    name: 'Rodes Harlin Hall',
    abbreviation: 'RHH',
    lat: 36.98857,
    lon: -86.45517,
    categories: ['residential'],
    department: 'Housing & Residence Life',
    description: 'A community-style hall featuring a large lobby, located near the valley and north campus entrance.',
  },
  {
    id: 'southwest',
    name: 'Southwest Hall',
    abbreviation: 'SWH',
    lat: 36.98437,
    lon: -86.45503,
    categories: ['residential'],
    department: 'Housing & Residence Life',
    description: 'A suite-style hall conveniently located near the Downing Student Union and Minton Hall.',
  },
  {
    id: 'zacharias',
    name: 'Zacharias Hall',
    abbreviation: 'ZAC',
    lat: 36.97971,
    lon: -86.45990,
    categories: ['residential'],
    department: 'Housing & Residence Life',
    description: 'A suite-style residence hall on the south end of campus, providing a comfortable living-learning environment.',
  },
];

export const getBuildingById = (id: string): CampusBuilding | undefined => {
  return CAMPUS_BUILDINGS.find(b => b.id === id);
};

export const getBuildingsByCategory = (category: BuildingCategory): CampusBuilding[] => {
  return CAMPUS_BUILDINGS.filter(b => b.categories.includes(category));
};
